/*
 * This file is generated by jOOQ.
*/
package com.example.pojo.tables;


import com.example.pojo.ExerciseTest;
import com.example.pojo.Indexes;
import com.example.pojo.Keys;
import com.example.pojo.tables.records.UsersInforRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersInfor extends TableImpl<UsersInforRecord> {

    private static final long serialVersionUID = -506509497;

    /**
     * The reference instance of <code>exercise_test.users_infor</code>
     */
    public static final UsersInfor USERS_INFOR = new UsersInfor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersInforRecord> getRecordType() {
        return UsersInforRecord.class;
    }

    /**
     * The column <code>exercise_test.users_infor.id</code>.
     */
    public final TableField<UsersInforRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>exercise_test.users_infor.user_name</code>.
     */
    public final TableField<UsersInforRecord, String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>exercise_test.users_infor.sex</code>.
     */
    public final TableField<UsersInforRecord, String> SEX = createField("sex", org.jooq.impl.SQLDataType.CHAR(2).nullable(false), this, "");

    /**
     * The column <code>exercise_test.users_infor.age</code>.
     */
    public final TableField<UsersInforRecord, Integer> AGE = createField("age", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>exercise_test.users_infor</code> table reference
     */
    public UsersInfor() {
        this(DSL.name("users_infor"), null);
    }

    /**
     * Create an aliased <code>exercise_test.users_infor</code> table reference
     */
    public UsersInfor(String alias) {
        this(DSL.name(alias), USERS_INFOR);
    }

    /**
     * Create an aliased <code>exercise_test.users_infor</code> table reference
     */
    public UsersInfor(Name alias) {
        this(alias, USERS_INFOR);
    }

    private UsersInfor(Name alias, Table<UsersInforRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsersInfor(Name alias, Table<UsersInforRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return ExerciseTest.EXERCISE_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USERS_INFOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsersInforRecord> getPrimaryKey() {
        return Keys.KEY_USERS_INFOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsersInforRecord>> getKeys() {
        return Arrays.<UniqueKey<UsersInforRecord>>asList(Keys.KEY_USERS_INFOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersInfor as(String alias) {
        return new UsersInfor(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersInfor as(Name alias) {
        return new UsersInfor(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersInfor rename(String name) {
        return new UsersInfor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersInfor rename(Name name) {
        return new UsersInfor(name, null);
    }
}
