/*
 * This file is generated by jOOQ.
*/
package com.example.pojo;


import com.example.pojo.tables.UsersInfor;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>exercise_test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USERS_INFOR_PRIMARY = Indexes0.USERS_INFOR_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USERS_INFOR_PRIMARY = Internal.createIndex("PRIMARY", UsersInfor.USERS_INFOR, new OrderField[] { UsersInfor.USERS_INFOR.ID }, true);
    }
}
