/*
 * This file is generated by jOOQ.
*/
package com.example.pojo;


import com.example.pojo.tables.UsersInfor;
import com.example.pojo.tables.records.UsersInforRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>exercise_test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UsersInforRecord> KEY_USERS_INFOR_PRIMARY = UniqueKeys0.KEY_USERS_INFOR_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<UsersInforRecord> KEY_USERS_INFOR_PRIMARY = Internal.createUniqueKey(UsersInfor.USERS_INFOR, "KEY_users_infor_PRIMARY", UsersInfor.USERS_INFOR.ID);
    }
}
