/*
 * This file is generated by jOOQ.
*/
package com.example.pojo;


import com.example.pojo.tables.UsersInfor;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in exercise_test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>exercise_test.users_infor</code>.
     */
    public static final UsersInfor USERS_INFOR = com.example.pojo.tables.UsersInfor.USERS_INFOR;
}
